### ISSUE TITLE
Definição da arquitetura

### ISSUE THREAD

**Issue by serralvo** [serralvo/mean-scrum#2]
Aquele MVC padrão? Ainda não explorei a stack, não conheço nenhuma outra arquitetura para o projeto.

**Comment by rafaelhgc** [comment]
Sim, será MVC.

**Comment by serralvo** [comment]
Acho essa arquitetura aceitável https://github.com/vmattos/mean-stack

**Comment by rafaelhgc** [comment]
Application
|____node_modules
|____public
|____|____img
|____|____js
|____|____css
|____routes
|____views
|____app.js

**Comment by serralvo** [comment]
Nice, close.
